# TURN برای کاربرانی که پشت NAT سخت‌گیر یا فایروال شرکتی هستند.
listening-port=3478
fingerprint
lt-cred-mech
realm=sr-connect

user-quota=12
total-quota=120

min-port=50300
max-port=50400

no-multicast-peers
no-cli
no-tlsv1
no-tlsv1_1

# جلوگیری از استفاده‌ی TURN برای رسیدن به شبکه‌ی داخلی سرور
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=127.0.0.0-127.255.255.255

syslog
